name: Pre-commit
on:
  schedule:
    # At 12:00 AM every day
    - cron: '0 0 * * *'

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pre-commit and autoupdate hooks
        run: |
          python -m pip install pre-commit
          pre-commit autoupdate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: pre-commit
          title: Update pre-commit hooks
          commit-message: update pre-commit hooks
          body: |
            Updating pre-commit hooks to latest. Creted by GH-Action
          labels: pre-commit
